[build]
  publish = "dist"
# 301s for legacy paths you mentioned
[[redirects]]
  from = "/services/index.shtml"
  to = "/"
  status = 301
[[redirects]]
  from = "/services/availability.shtml"
  to = "/"
  status = 301
[[redirects]]
   from = "/why-woodco/video-tour/"
   to="/"
   status = 301
# Security headers (nice-to-have)
[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Frame-Options = "SAMEORIGIN"
